import { motion } from 'framer-motion'
import { AlertTriangle, Info, CheckCircle2 } from 'lucide-react'

type Severity = 'high' | 'medium' | 'low'

interface Limitation {
  title: string
  detail: string
  severity: Severity
}

const limitations: Limitation[] = [
  {
    title: 'Single-Node kind Cluster',
    detail: 'All experiments on a single-node kind cluster. Multi-node scheduling, network partitions, and multi-AZ HA not tested.',
    severity: 'high',
  },
  {
    title: 'Synthetic Locust Load',
    detail: 'Load generated by Locust synthetic traffic. Real user traffic patterns (session affinity, cache effects) differ significantly.',
    severity: 'high',
  },
  {
    title: 'Deterministic N=10 Trials',
    detail: 'The N=10 evaluation produced σ = 0 across all cells; Wilcoxon p and Cohen\'s d are not informative. The harness adds Gaussian noise (σ=0.05) but the operator responses are deterministic given the seeds.',
    severity: 'medium',
  },
  {
    title: 'Day-15 AI Failure Is Real',
    detail: 'The v1 AI controller produced 100% errors and stuck at replicas ≤ 2 across all 9 of 9 N=3 runs (data/evaluation/comparison_results_N3.csv:20-28). The safety shield absorbed it, but the v1 decision logic was load-first and required a Day-15 -> Day-18 rework.',
    severity: 'high',
  },
  {
    title: 'v2 Anomaly Detection: 1.2% Organic Rate',
    detail: 'v2 labeling heuristic (spike=anomaly, idle=anomaly, steady=normal) produces feature distributions with low separation. Anomaly detection is honest but weak.',
    severity: 'medium',
  },
  {
    title: 'No Multi-AZ / No Production Traffic',
    detail: 'No multi-AZ cluster, no real production traffic. Microservices run inside a kind cluster only.',
    severity: 'medium',
  },
  {
    title: 'MIT / LICENSE File Pending',
    detail: 'A LICENSE file is not yet committed at the repo root. The codebase is provided as research-prototype code; treat it accordingly.',
    severity: 'low',
  },
]

const severityClasses: Record<Severity, string> = {
  high: 'bg-red-50 text-red-700 border-red-200',
  medium: 'bg-amber-50 text-amber-700 border-amber-200',
  low: 'bg-surface-100 text-text-secondary border-border',
}

const severityLabel: Record<Severity, string> = {
  high: 'High',
  medium: 'Medium',
  low: 'Low',
}

export function Limitations() {
  return (
    <section id="limitations" className="py-20 md:py-28 lg:py-32 px-6 md:px-12 max-w-6xl mx-auto" aria-labelledby="limitations-heading">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-100px' }}
        transition={{ duration: 0.6 }}
        className="text-center max-w-3xl mx-auto mb-16"
      >
        <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-red-50 text-red-700 text-sm font-medium border border-red-200 mb-4">
          Limitations
        </span>
        <h2 id="limitations-heading" className="text-3xl md:text-4xl lg:text-5xl font-bold text-text-primary leading-tight mb-6">
          Limitations &amp; <span className="text-red-600">Threats to Validity</span>
        </h2>
        <p className="text-lg text-text-secondary max-w-2xl mx-auto leading-relaxed">
          We document known weaknesses honestly. Reviewers should weigh these against the contributions.
        </p>
      </motion.div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {limitations.map((limitation, index) => (
          <motion.article
            key={limitation.title}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-50px' }}
            transition={{ delay: index * 0.1, duration: 0.5 }}
            className="bg-white rounded-xl border border-border p-6 hover:shadow-lg transition-shadow duration-300"
          >
            <div className="flex items-start gap-3 mb-3">
              <AlertTriangle className="w-5 h-5 flex-shrink-0 text-red-600" />
              <h3 className="font-semibold text-text-primary">{limitation.title}</h3>
            </div>
            <p className="text-text-secondary text-sm mb-3 leading-relaxed">{limitation.detail}</p>
            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${severityClasses[limitation.severity]}`}>
              {severityLabel[limitation.severity]}
            </span>
          </motion.article>
        ))}
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-100px' }}
        className="mt-16 grid md:grid-cols-2 gap-6"
      >
        <div className="p-6 bg-amber-50 rounded-2xl border border-amber-200">
          <div className="flex items-start gap-3">
            <Info className="w-6 h-6 flex-shrink-0 text-amber-600" />
            <div>
              <h3 className="font-semibold text-amber-800 mb-2">What This Means for Reviewers</h3>
              <ul className="list-disc list-inside text-text-secondary text-sm space-y-1">
                <li>The TLA+ safety proof is workload-independent — it checks the operator's decision logic, not the workload metrics.</li>
                <li>Empirical results are workload-specific (Flask + SQLite, kind, Locust).</li>
                <li>Comparison metrics are proxies for "operator quality", not absolute production benchmarks.</li>
                <li>All claims trace to reproducible artifacts in <code>evidence-freeze.md</code>.</li>
              </ul>
            </div>
          </div>
        </div>

        <div className="p-6 bg-green-50 rounded-2xl border border-green-200">
          <div className="flex items-start gap-3">
            <CheckCircle2 className="w-6 h-6 flex-shrink-0 text-green-700" />
            <div>
              <h3 className="font-semibold text-green-800 mb-2">What Stays True Despite All This</h3>
              <ul className="list-disc list-inside text-text-secondary text-sm space-y-1">
                <li>The 273,702-state TLC trace is reproducible.</li>
                <li>The 53/53 reachable-state composition trace is reproducible.</li>
                <li>The Day-15 N=3 100% error rate is reproducible.</li>
                <li>Every number on this page traces to a saved file (57 sourced / 0 unsourced).</li>
              </ul>
            </div>
          </div>
        </div>
      </motion.div>
    </section>
  )
}
