import { motion } from 'framer-motion'
import { AlertTriangle, Info } from 'lucide-react'

type Severity = 'high' | 'medium' | 'low'

interface Limitation {
  title: string
  detail: string
  severity: Severity
}

const limitations: Limitation[] = [
  {
    title: 'Single-Node Kind Cluster',
    detail: 'All experiments run on single-node kind. Multi-node scheduling, network partitions, and multi-AZ HA not tested.',
    severity: 'high',
  },
  {
    title: 'Synthetic Locust Load',
    detail: 'Load generated by Locust synthetic traffic. Real user traffic patterns (session affinity, cache effects) differ significantly.',
    severity: 'high',
  },
  {
    title: 'Single Workload Family',
    detail: 'Only Flask + SQLite workload tested. Results may not generalize to CPU-bound, I/O-bound, or GPU workloads.',
    severity: 'medium',
  },
  {
    title: 'v1 AI Broken Under Load',
    detail: 'Day-8 detector (trained on 33 rows) flags almost every window as anomalous in idle conditions, saturating the cooldown and producing 100% error rate in N=3.',
    severity: 'high',
  },
  {
    title: 'v2 Anomaly Detection Only 1.2%',
    detail: 'v2 labeling heuristic (spike=anomaly, idle=anomaly, steady=normal) produces feature distributions with low separation.',
    severity: 'high',
  },
  {
    title: 'No .tex Compilation',
    detail: 'IEEE paper is Markdown (.md). LaTeX not installed; pandoc conversion to .tex needed for formal submission.',
    severity: 'low',
  },
  {
    title: 'No Production Deployment',
    detail: 'No multi-node cluster, no real production traffic, no multi-AZ HA. Microservices in kind only.',
    severity: 'high',
  },
  {
    title: 'No Independent Reproduction',
    detail: 'bootstrap_vm.sh enables it, but no external party has independently reproduced results yet.',
    severity: 'medium',
  },
]

const severityClasses: Record<Severity, string> = {
  high: 'bg-red-50 text-red-700 border-red-200',
  medium: 'bg-amber-50 text-amber-700 border-amber-200',
  low: 'bg-green-50 text-green-700 border-green-200',
}

const severityLabel: Record<Severity, string> = {
  high: 'High',
  medium: 'Medium',
  low: 'Low',
}

export function Limitations() {
  return (
    <section id="limitations" className="py-20 md:py-28 lg:py-32 px-6 md:px-12 max-w-7xl mx-auto" aria-labelledby="limitations-heading">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-100px' }}
        transition={{ duration: 0.6 }}
        className="text-center max-w-3xl mx-auto mb-16"
      >
        <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-red-50 text-red-700 text-sm font-medium border border-red-200 mb-4">
          Limitations
        </span>
        <h2 id="limitations-heading" className="text-3xl md:text-4xl lg:text-5xl font-bold text-text-primary leading-tight mb-6">
          Limitations & <span className="text-red-600">Threats to Validity</span>
        </h2>
        <p className="text-lg text-text-secondary max-w-2xl mx-auto leading-relaxed">
          We document known weaknesses honestly. Reviewers should weigh these against the contributions.
        </p>
      </motion.div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {limitations.map((limitation, index) => (
          <motion.article
            key={limitation.title}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-50px' }}
            transition={{ delay: index * 0.1, duration: 0.5 }}
            className="bg-white rounded-xl border border-border p-6 hover:shadow-lg transition-shadow duration-300"
          >
            <div className="flex items-start gap-3 mb-3">
              <AlertTriangle className="w-5 h-5 flex-shrink-0 text-red-600" />
              <h3 className="font-semibold text-text-primary">{limitation.title}</h3>
            </div>
            <p className="text-text-secondary text-sm mb-3">{limitation.detail}</p>
            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${severityClasses[limitation.severity]}`}>
              {severityLabel[limitation.severity]}
            </span>
          </motion.article>
        ))}
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-100px' }}
        className="mt-16 p-6 bg-amber-50 rounded-2xl border border-amber-200"
      >
        <div className="flex items-start gap-3">
          <Info className="w-6 h-6 flex-shrink-0 text-amber-600" />
          <div>
            <h3 className="font-semibold text-amber-800 mb-2">What This Means for Reviewers</h3>
            <p className="text-text-secondary text-sm mb-2">
              We do not claim production readiness. This is a research prototype demonstrating
              the <strong>feasibility</strong> of combining online ML with formal verification
              for Kubernetes auto-scaling and healing.
            </p>
            <ul className="list-disc list-inside text-text-secondary text-sm space-y-1">
              <li>The TLA+ safety proof is workload-independent — it checks the operator's decision logic, not the workload metrics.</li>
              <li>Empirical results are workload-specific (Flask + SQLite, kind, Locust).</li>
              <li>Comparison metrics (scaling lag, healing time) are proxies for "operator quality".</li>
              <li>All claims traceable to reproducible artifacts: <code>bootstrap_vm.sh</code>, <code>data/evaluation/</code>, <code>tests/</code>.</li>
            </ul>
          </div>
        </div>
      </motion.div>
    </section>
  )
}